from __future__ import annotations

import json


EXPECTED_FIELDS = [
    "objective_id",
    "record_id",
    "rank",
    "owner",
    "repo_name",
    "repository",
    "url",
    "description",
    "language",
    "stars",
    "forks",
    "stars_today",
    "captured_at",
    "source_url",
    "raw_text_hash",
]


def github_trending_files(objective_id: str = "obj_github_trending") -> dict[str, str]:
    manifest = {
        "name": "github_trending_crawler",
        "version": "2026.06.28",
        "runtime": "python3",
        "entry_command": "python crawler.py",
        "hashslip": {"enabled": True},
        "preflight": {"required": True, "command": "python crawler.py --preflight"},
        "safety": {
            "allowed_domains": ["github.com"],
            "blocked_private_networks": True,
            "disable_shell": True,
            "network_egress_policy": "manifest_only",
            "secrets_access": "none",
        },
    }
    schema = {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "type": "object",
        "required": EXPECTED_FIELDS,
        "properties": {field: {"type": ["string", "number", "integer", "null"]} for field in EXPECTED_FIELDS},
        "additionalProperties": True,
    }
    sources = [
        {
            "name": "GitHub Trending repositories page",
            "priority": 1,
            "access_type": "html",
            "trust_level": "primary",
            "allowed_domains": ["github.com"],
            "url": "https://github.com/trending",
            "risk": "low",
            "metadata": {"profile_id": "github_trending_html", "parser": "github_trending_repositories"},
        }
    ]
    crawler = CRAWLER.replace('OBJECTIVE_ID = "obj_github_trending"', f"OBJECTIVE_ID = {json.dumps(objective_id)}")
    return {
        "crawler.py": crawler,
        "manifest.json": json.dumps(manifest, ensure_ascii=True, indent=2) + "\n",
        "requirements.txt": "",
        "tests/test_parser.py": TESTS,
        "fixtures/sample.html": SAMPLE_HTML,
        "fixtures/sample.csv": SAMPLE_CSV,
        "schemas/output.schema.json": json.dumps(schema, ensure_ascii=True, indent=2) + "\n",
        "sources.json": json.dumps(sources, ensure_ascii=True, indent=2) + "\n",
        "CHANGELOG.md": "# Changelog\n\n- 2026.06.28: generated by DoCode for CIS GitHub Trending.\n",
        "README.md": "# GitHub Trending Crawler\n\nAraneae-ready crawler generated by DoCode for CIS.\n",
    }


CRAWLER = r'''
from __future__ import annotations

import argparse
import csv
import hashlib
import html
import json
import re
from datetime import datetime, timezone
from pathlib import Path
from urllib.request import Request, urlopen

OBJECTIVE_ID = "obj_github_trending"
SOURCE_URL = "https://github.com/trending"
FIELDS = ["objective_id", "record_id", "rank", "owner", "repo_name", "repository", "url", "description", "language", "stars", "forks", "stars_today", "captured_at", "source_url", "raw_text_hash"]


def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def clean_text(value: str) -> str:
    value = re.sub(r"<[^>]+>", " ", value)
    return re.sub(r"\s+", " ", html.unescape(value)).strip()


def parse_int(value: str) -> int:
    text = value.strip().replace(",", "").lower()
    if not text:
        return 0
    multiplier = 1
    if text.endswith("k"):
        multiplier = 1000
        text = text[:-1]
    try:
        return int(float(text) * multiplier)
    except ValueError:
        return 0


def parse_trending_repositories(document: str, source_url: str = SOURCE_URL) -> list[dict]:
    captured_at = now_iso()
    article_pattern = re.compile(r"<article[\s\S]*?</article>", re.IGNORECASE)
    articles = article_pattern.findall(document)
    if not articles:
        articles = re.findall(r"<li[\s\S]*?</li>", document, flags=re.IGNORECASE)
    records = []
    for index, block in enumerate(articles, start=1):
        link_match = re.search(r'href="(/[^/\s"]+/[^/\s"]+)"', block)
        if not link_match:
            link_match = re.search(r'href="https://github\.com/([^/\s"]+/[^/\s"]+)"', block)
        if not link_match:
            continue
        href = link_match.group(1)
        repository = href.strip("/").replace("https://github.com/", "").split("?")[0]
        parts = repository.split("/")
        if len(parts) < 2:
            continue
        owner, repo_name = parts[0], parts[1]
        description_match = re.search(r'<p[^>]*class="[^"]*col-9[^"]*"[^>]*>([\s\S]*?)</p>', block)
        if not description_match:
            description_match = re.search(r"<p[^>]*>([\s\S]*?)</p>", block)
        language_match = re.search(r'itemprop="programmingLanguage"[^>]*>(.*?)</', block, flags=re.IGNORECASE)
        star_matches = re.findall(r'aria-label="([0-9.,kK]+)\s+stars?"|>([0-9.,kK]+)</a>', block, flags=re.IGNORECASE)
        numeric_values = [parse_int(a or b) for a, b in star_matches if parse_int(a or b)]
        today_match = re.search(r"([0-9,]+)\s+stars?\s+today", block, flags=re.IGNORECASE)
        raw_text = clean_text(block)
        raw_hash = hashlib.sha256(raw_text.encode("utf-8")).hexdigest()
        records.append({
            "objective_id": OBJECTIVE_ID,
            "record_id": f"{owner}/{repo_name}:{raw_hash[:12]}",
            "rank": len(records) + 1,
            "owner": owner,
            "repo_name": repo_name,
            "repository": f"{owner}/{repo_name}",
            "url": f"https://github.com/{owner}/{repo_name}",
            "description": clean_text(description_match.group(1)) if description_match else "",
            "language": clean_text(language_match.group(1)) if language_match else "",
            "stars": numeric_values[0] if numeric_values else 0,
            "forks": numeric_values[1] if len(numeric_values) > 1 else 0,
            "stars_today": parse_int(today_match.group(1)) if today_match else 0,
            "captured_at": captured_at,
            "source_url": source_url,
            "raw_text_hash": raw_hash,
        })
    return records


def fetch_source() -> str:
    request = Request(SOURCE_URL, headers={"User-Agent": "cis-docode-github-trending/1.0", "Accept": "text/html,*/*"})
    with urlopen(request, timeout=20) as response:
        return response.read(2_000_000).decode("utf-8", errors="replace")


def load_fixture() -> str:
    return Path("fixtures/sample.html").read_text(encoding="utf-8")


def write_csv(records: list[dict], path: str = "github_trending.csv") -> None:
    with open(path, "w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=FIELDS)
        writer.writeheader()
        writer.writerows(records)


def emit_sink(records: list[dict]) -> None:
    sink = Path(".araneae/sink/events.jsonl")
    sink.parent.mkdir(parents=True, exist_ok=True)
    with sink.open("w", encoding="utf-8") as handle:
        for record in records:
            payload = {"type": "structured", "data": {"instance_id": "cis", "schema_id": "github_trending", "data": record}}
            handle.write(json.dumps(payload, ensure_ascii=False, sort_keys=True) + "\n")
    print(f"sink queued structured={len(records)}")


def validate(records: list[dict]) -> None:
    if not records:
        raise ValueError("no GitHub Trending records parsed")
    for record in records:
        missing = [field for field in FIELDS if field not in record]
        if missing:
            raise ValueError("missing fields: " + ", ".join(missing))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--preflight", action="store_true")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()
    if args.preflight or args.dry_run:
        document = load_fixture()
    else:
        try:
            document = fetch_source()
        except Exception:
            document = load_fixture()
    records = parse_trending_repositories(document)
    validate(records)
    if args.preflight:
        print(json.dumps({"status": "preflight_ok", "records": len(records)}, sort_keys=True))
        return 0
    write_csv(records)
    emit_sink(records)
    print(json.dumps({"status": "ok", "records": len(records)}, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''.lstrip()


TESTS = r'''
from pathlib import Path
import sys
import unittest

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from crawler import FIELDS, parse_trending_repositories


class ParserTest(unittest.TestCase):
    def test_parse_sample_trending_repositories(self):
        document = Path("fixtures/sample.html").read_text(encoding="utf-8")
        records = parse_trending_repositories(document)
        self.assertGreaterEqual(len(records), 2)
        first = records[0]
        self.assertEqual(first["repository"], "openai/codex")
        self.assertEqual(first["language"], "Python")
        for field in FIELDS:
            self.assertIn(field, first)


if __name__ == "__main__":
    unittest.main()
'''.lstrip()


SAMPLE_HTML = r'''
<!doctype html>
<html>
  <head><title>Trending repositories on GitHub today</title></head>
  <body>
    <main>
      <article class="Box-row">
        <h2><a href="/openai/codex">openai / codex</a></h2>
        <p class="col-9 color-fg-muted my-1 pr-4">Coding agent for practical software engineering.</p>
        <span itemprop="programmingLanguage">Python</span>
        <a href="/openai/codex/stargazers">12,345</a>
        <a href="/openai/codex/forks">678</a>
        <span>123 stars today</span>
      </article>
      <article class="Box-row">
        <h2><a href="/example/trending">example / trending</a></h2>
        <p class="col-9 color-fg-muted my-1 pr-4">Example trending repository.</p>
        <span itemprop="programmingLanguage">Go</span>
        <a href="/example/trending/stargazers">2,345</a>
        <a href="/example/trending/forks">89</a>
        <span>45 stars today</span>
      </article>
    </main>
  </body>
</html>
'''.lstrip()


SAMPLE_CSV = """rank,owner,repo_name,repository,url,description,language,stars,forks,stars_today,captured_at,source_url,raw_text_hash
1,openai,codex,openai/codex,https://github.com/openai/codex,Coding agent for practical software engineering.,Python,12345,678,123,2026-06-28T00:00:00+00:00,https://github.com/trending,fixture
"""
